### PR TITLE
Issue/implement "setup configuration" management command

### LINKED ISSUE #87: Implement "setup_configuration" management command
Should be the same approach as in Open Zaak, so that CI/CD can configure instances without manual intervention required.

### PR DESCRIPTION
**Pull request by Nath82**
Fixes #87 -- Create 2 management command to setup the configuration of open-notifications

### CODE REVIEW

**Comment by alextreme** [comment]
@sergei-maertens let me know if you want me to put someone else on this PR to round this up.

**Comment by sergei-maertens** [comment]
> @sergei-maertens let me know if you want me to put someone else on this PR to round this up.

Does @annashamray have time?

**Comment by annashamray** [comment]
@sergei-maertens @alextreme I can take a look

**Comment by annashamray** [comment]
Superseded by https://github.com/open-zaak/open-notificaties/pull/131

**Pull request closed without merging**
