### PR TITLE
Prepare upgrade to Django 4.2

### LINKED ISSUE #124: Upgrade to Django 4.2 in Open Notificaties
Dependencies:
- [x] `django-auth-adfs-db`: unsupported, but seems to not be relevant anymore? See `uninstall_adfs.sh`
- [x] `django-axes`: can be updated, some settings were deprecated. See https://github.com/open-formulieren/open-forms/commit/73ea9d739bae2ecf4d6fa8e91090cc4a708ebe0a for an example
- [x] `django-choices`: not used, can be removed
- [x] `django-cors-headers`: can be updated
- [x] `django-markup`: can be removed? I don't see any references in the code
- [x] `django-redis`: can be updated
- [x] `django-admin-index`: can be updated, iirc some changes are needed
- [x] `mozilla-django-oidc-db`: can be updated, need to check changelog 
- [x] `django-log-outgoing-requests`: can be updated, check this [breaking change](https://github.com/maykinmedia/django-log-outgoing-requests/blob/main/CHANGELOG.rst#050-2023-08-15) before
- [ ] `gemma-zds-client`: Should be updated to 2.x, so that `zgw-consumers` can also be bumped.
- [ ] `drf-yasg`: should switch to `drf-spectacular`, requires some work

Deprecation warnings:

- [ ] A bunch of deprecation warnings related to ZDS: in particular, the use of the mock client. Should probably switch to the ape pie client but requires some work.
- [x] `django-relativedelta` makes use of `uget*`; should be fixed by upgrading `zgw-consumers`.

### PR DESCRIPTION
**Pull request by Viicos**
Fixes #124

### CODE REVIEW

**Review by sergei-maertens — COMMENTED** [review]
I would advise only upgrading packages related to django itself, so things like black/isort etc. you really want to do in a separate PR

Sorting out the django-related packages will already be complicated enough. I'd even go so far as to make a PR per package upgrade.

**Comment by Viicos** [comment]
> I would advise only upgrading packages related to django itself, so things like black/isort etc. you really want to do in a separate PR
> 
> Sorting out the django-related packages will already be complicated enough. I'd even go so far as to make a PR per package upgrade.

That's why I went with separate commits for each

**Review by annashamray — COMMENTED** [review]
@Viicos Could you please rebase on main and resolve the conflicts?

**Comment by Viicos** [comment]
@annashamray The Django 4.2 upgrade will have to be done in a separate PR -- I don't have more time to work on this, and there are still things to be handled (especially zgw consumers/zds client)

**Review by annashamray — APPROVED** [review]

**Pull request merged**
