### PR TITLE
Issue/add elastic apm support

### PR DESCRIPTION
**Pull request by Nath82**
#98 Adding elastic apm support to the project to monitor application performance

### CODE REVIEW

**Comment by alextreme** [comment]
@Nath82 please expand your PR description to be clear. It should be more than a reference to an issue.

**Comment by Nath82** [comment]
> @Nath82 please expand your PR description to be clear. It should be more than a reference to an issue.

Is it ok like this? I do not see how I can explain it any further as it seems obvious to me?

**Comment by alextreme** [comment]
> > @Nath82 please expand your PR description to be clear. It should be more than a reference to an issue.
> 
> Is it ok like this? I do not see how I can explain it any further as it seems obvious to me?

This is fine thanks

**Comment by alextreme** [comment]
Also ensure the transaction sample rate is configurable via envvars (eg: `config("")` )

**Review by alextreme — APPROVED** [review]

**Comment by alextreme** [comment]
Discussed that this PR was prematurely merged, we should wait for Anna's confirmation to do this

**Pull request merged**
